### PR TITLE
Update DIP-6 with latest links

### PR DESCRIPTION
**Pull request by AW-STJ**
Updated the old links as we moved the tokenscript website to a new domain.

### CODE REVIEW

**Review by ligi — CHANGES_REQUESTED** [review]
thanks!
One more after the PR:
```

FILE: DIPs/DIP-6.md
[✖] http://attestation.id → Status: 0 Error: getaddrinfo ENOTFOUND attestation.id
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'attestation.id'
}
```

**Comment by AW-STJ** [comment]
> One more after the PR:

> FILE: DIPs/DIP-6.md
> [✖] http://attestation.id → Status: 0 Error: getaddrinfo ENOTFOUND attestation.id
>    

Thanks for the quick review @ligi. The link is correct and we will get the website up and running as part of the deliverables towards the end of January.

**Comment by ligi** [comment]
the problem is:
 a) it makes our CI quite unhappy - and I would like a happy CI
 b) we have a broken link and the context:
> The email attestation service created by AlphaWallet will allow the attendees to claim their attestations at http://attestation.id. 
also does not indicate it is down.
Can we just delete the link until it is available?

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
Hey - just saw that  https://attestation.id has been in there twice
also:
 https://GitHub.com/AlphaWallet/blockchain-attestation/blob/master/use-cases/send-ether-by-identifier-attestation.md → Status: 404

**Pull request merged**
